### ISSUE TITLE
Add API documentation for all routes

### ISSUE THREAD

**Issue by sharmaaditya570191** [sharmaaditya570191/BossY#1]
**1.** Create a `README.md` file in the server directory. 
**2.** Code for the entire API is in the `server` directory. 
**3.** Describe functionality and behaviour of all routes and the response type when the user hits the endpoints.(include screenshots of request-response with morgan('tiny') if possible)

**Comment by Endowmissy** [comment]
I am interested in working on this issue from GSSoC20

**Comment by sharmaaditya570191** [comment]
Sure! Please go ahead @Endowmissy .

**Comment by abhishekjain35** [comment]
I would like to work on this issue as a part of GsSoc20

**Comment by punisherz** [comment]
Can i work on this issue? @sharmaaditya570191
