### ISSUE TITLE
Secure the web app

### ISSUE THREAD

**Issue by chauhanparth210** [sharmaaditya570191/BossY#11]
Hello @sharmaaditya570191, I am Parth and I want to contribute to this project. Can I add [Helmet.js](https://helmetjs.github.io/) to prevent DNS attack and to prevent the web app from being hacked.

**Comment by sharmaaditya570191** [comment]
Yes sure. Go ahead.

**Comment by chauhanparth210** [comment]
@sharmaaditya570191  I think you should add ESLint and Prittier file for maintain and scale your code.

**Comment by sharmaaditya570191** [comment]
Yes you can add the files if you would like to work on it @chauhanparth210 .Thanks.

**Comment by sharmaaditya570191** [comment]
Hi @chauhanparth210 . Are you still working on this?

**Comment by cynideschizo** [comment]
now i started working

**Comment by chauhanparth210** [comment]
Ok @cynideschizo , go ahead.

**Comment by chauhanparth210** [comment]
@

**Comment by chauhanparth210** [comment]
@cynideschizo , go ahead.
