### ISSUE TITLE
Make a document CONTRIBUTING.md

### ISSUE THREAD

**Issue by vipuldcoder** [sharmaaditya570191/BossY#15]
Hello Everyone,
This is a new document that helps the open source contributors to understand and learn. How to get involved to contribute to this project. This makes a document helps us the collaborator to understand what this project is and how they can contribute towards it.
Thank You

**Comment by sharmaaditya570191** [comment]
Anyone interested in this?

**Comment by raa-zez** [comment]
I would like to work on this issue @sharmaaditya570191

**Comment by jamesjose03** [comment]
@sharmaaditya570191 I would like to work on this issue

**Comment by Basilleaf24** [comment]
@sharmaaditya570191 I would like to work on this, this is going to be my first issue, pls assign it to me

**Comment by punisherz** [comment]
can i work on this issue? @sharmaaditya570191

**Comment by sharmaaditya570191** [comment]
@vipuldcoder are you still working on this?

**Comment by shwetagurnani** [comment]
I want to work on this issue.Please assign it to me.

**Comment by Chetanjain10** [comment]
I would like to work on this, this is going to be my first issue, pls assign it to me
