### ISSUE TITLE
Design a logo for BOSSY

### ISSUE THREAD

**Issue by sharmaaditya570191** [sharmaaditya570191/BossY#16]
This includes designing a nice and eye-catching logo for the project. The logo file type should be `.png`. You can suggest different file types along with the benefits of using them. First 4-5 interested people can work on this issue and we can go with the best design.

**Comment by raa-zez** [comment]
I would like to work on this issue @sharmaaditya570191

**Comment by ranjal007** [comment]
I need to work on this issue. Please assign it to me.

**Comment by sharmaaditya570191** [comment]
@raa-zez @ranjal007 you can go ahead with the designs. As I mentioned earlier we will together decide which designs we need to take forward.

**Comment by ranjal007** [comment]
Okay, sure I will try my best to make an attractive logo.

**Comment by goyalmuskan** [comment]
May I also work on this issue? @sharmaaditya570191

**Comment by punisherz** [comment]
I am interested! @sharmaaditya570191

**Comment by punisherz** [comment]
do i have to be assigned to suggest logo designs? @sharmaaditya570191

**Comment by nitashadhingra** [comment]
i'd like to contribute
