### ISSUE TITLE
Readme doesn't have proper guide for development setup contribution.

### ISSUE THREAD

**Issue by imrishabh18** [sharmaaditya570191/BossY#18]
Many people are having issue with setting up the development environment for contribution.

**Comment by imrishabh18** [comment]
I am working on this.

**Comment by Satyam3976** [comment]
I want to work on this issue. @sharmaaditya570191 Please asign me this issue.

**Comment by imrishabh18** [comment]
@Satyam3976 I have already made a PR foe this.

**Comment by punisherz** [comment]
@imrishabh18 is your pr merged? 
meanwhile can i start on this sir @sharmaaditya570191

**Comment by imrishabh18** [comment]
@punisherz No not yet
