### ISSUE TITLE
Provide a TOC for README.md file

### ISSUE THREAD

**Issue by jamesjose03** [sharmaaditya570191/BossY#20]
At present, there is no table of contents for the README file. 
TOC can provide easier navigation through the README file.

**Comment by jamesjose03** [comment]
@sharmaaditya570191 I would like to work on this issue

**Comment by Basilleaf24** [comment]
@jamesjose03 @sharmaaditya570191 I would like to work on this, I haven't been assigned any issues,
pls assign me this issue

**Comment by jamesjose03** [comment]
@Basilleaf24 Sorry, I am already working on this issue.

**Comment by sharmaaditya570191** [comment]
@jamesjose03 what exactly do you plan to add in the `README`. Please keep in mind that we should keep the instructions in the `README` short and clear so that people tend to read the file.

**Comment by jamesjose03** [comment]
@sharmaaditya570191 To add a table of contents in the readme just like how standard README files are maintained. It provides an easier navigation through the README and people can understand what are the main topics that are included in the README file.
For example,
![image](https://user-images.githubusercontent.com/31133182/76517000-7d5d1600-6482-11ea-81b0-03a49d9b838a.png)

**Comment by sharmaaditya570191** [comment]
Thanks for your suggestion @jamesjose03 . Here we don't have a long `README.md` so their is no need for TOC. We may open this at a later stage. Closing it for now.
