### ISSUE TITLE
Convert Idea component to function component

### ISSUE THREAD

**Issue by sharmaaditya570191** [sharmaaditya570191/BossY#26]
Currently this is a class component. Convert the existing code by implementing it as a function component in React.

**Comment by Satyam3976** [comment]
I can work on this issue.Please assign it to me

**Comment by BhuwanChandra** [comment]
@sharmaaditya570191 I would like to work on this issue. please assign this to me.

**Comment by Ruchika30** [comment]
I can work on this issue. Please assign it to me if not done . @sharmaaditya570191
