### ISSUE TITLE
Convert Minion component to function component

### ISSUE THREAD

**Issue by sharmaaditya570191** [sharmaaditya570191/BossY#27]
Currently this is a class component. Convert the existing code by implementing it as a function component in React.

**Comment by imrishabh18** [comment]
Hey, i will work on this issue

**Comment by sharmaaditya570191** [comment]
@imrishabh18 I have assigned you another issue. Please complete that first.

**Comment by Satyam3976** [comment]
I can work on this issue.Please assign it to me.

**Comment by BhuwanChandra** [comment]
@sharmaaditya570191 I would like to work on this issue. please assign this to me.
