### ISSUE TITLE
Convert Work component to function component

### ISSUE THREAD

**Issue by sharmaaditya570191** [sharmaaditya570191/BossY#29]
Currently this is a class component. Convert the existing code by implementing it as a function component in React.

**Comment by Satyam3976** [comment]
I can work on this issue.Please assign it to me.

**Comment by shwetagurnani** [comment]
I can work on this issue.Please assign

**Comment by ashishnagpal2498** [comment]
Can I work on this issue as part of GSSOC 20 ?
