### ISSUE TITLE
Migrate from react-router to reach-router

### ISSUE THREAD

**Issue by sharmaaditya570191** [sharmaaditya570191/BossY#31]
`reach-router` is a better router in terms of accessibility and comes from the same person who developed `react-router` and tries to cover the shortcomings of `react-router`. `reach` has a different path-scoring algorithm which makes it more specific.
The task is to replace every usage of `react-router` with `reach-router` and ensure that nothing breaks in the process.

**Comment by BhuwanChandra** [comment]
@sharmaaditya570191 I would like to work on this. please assign this to me

**Comment by dibakar95** [comment]
@sharmaaditya570191 has the issue been fixed?
