### ISSUE TITLE
Add script to format and lint files with prettier-standard

### ISSUE THREAD

**Issue by sharmaaditya570191** [sharmaaditya570191/BossY#33]
Add `prettier-standard` code formatter to the project which will format with `prettier` and lint with `ESLint` by following the instructions [here](https://github.com/sheerun/prettier-standard). Then add a small `format` script in the `package.json` so that contributors can run this script before making a pull request.

**Comment by imrishabh18** [comment]
Working on this issue

**Comment by imrishabh18** [comment]
@sharmaaditya570191 Hey, can you help me when i was trying to create a new branch and pushing this change of adding prettier-standard . When i was creating a PR it was also showing previous commits that i made of login and signup page. How to just create a PR with this change ? I searched a lot about this but still couldn't figure out that cherry-picking command.
