### ISSUE TITLE
Create a pull request template for the repository

### ISSUE THREAD

**Issue by sharmaaditya570191** [sharmaaditya570191/BossY#34]
This includes creating a pull request template for the contributors.

**Comment by Aman-Codes** [comment]
I am a GSSOC 2020 participant and I would love to work on it. Please assign it to me.

**Comment by Kuljeet-123** [comment]
@sharmaaditya570191  I'm a GSSOC'20 participant I would like to work on this issue...can you please assign me this.

**Comment by Dishebh** [comment]
@sharmaaditya570191 can I work on this?
