### ISSUE TITLE
Create a bug reporting template for the repository

### ISSUE THREAD

**Issue by sharmaaditya570191** [sharmaaditya570191/BossY#35]
This includes creating a template for reporting bugs.

**Comment by Aman-Codes** [comment]
I am a GSSOC 2020 participant and I would love to work on it. Please assign it to me.

**Comment by shwetagurnani** [comment]
I am a GSSOC participant.Please assign it to me.It will be my first contribution to the project

**Comment by jamesjose03** [comment]
@sharmaaditya570191 I would like to work on this issue. I am a GSSOC participant. Please assign this issue to me.

**Comment by suhanichawla** [comment]
Sure go ahead
