### ISSUE TITLE
Add security to the web app

### ISSUE THREAD

**Issue by sharmaaditya570191** [sharmaaditya570191/BossY#37]
This includes integrating [helmet.js](https://helmetjs.github.io/) in the express app to enhance security with respect to various types of attacks.

**Comment by imrishabh18** [comment]
Working on this.

**Comment by imrishabh18** [comment]
@sharmaaditya570191 Hey, see this https://github.com/sharmaaditya570191/BossY/commit/e1a52a8e81def6e8b85ef697491d2005c73ebcbe

**Comment by sharmaaditya570191** [comment]
@imrishabh18 I have already assigned you to another issue. Please try to complete 1 issue first.

**Comment by imrishabh18** [comment]
@sharmaaditya570191 Sorry,I have already added the PR for this.

**Comment by sharmaaditya570191** [comment]
I have closed that PR @imrishabh18

**Comment by punisherz** [comment]
i want to work on this issue @sharmaaditya570191

**Comment by sharmaaditya570191** [comment]
You have already been assigned an issue @punisherz . Please try to complete that first.

**Comment by sharmakeshav10** [comment]
I'd like to work on this issue.
