### ISSUE TITLE
Add a button to change modes between Day and Night mode.

### ISSUE THREAD

**Issue by somyaranjan26** [sharmaaditya570191/BossY#61]
Add Toggle button which is use to change colour theme from day to night mode and via-versa (i.e. from light theme to dark theme)

**Comment by Adyasha8105** [comment]
please assign this issue to me @somyaranjan26

**Comment by Adyasha8105** [comment]
I will work on both the issue.

**Comment by BhuwanChandra** [comment]
@somyaranjan26 I would like to work on this issue. please assign this to me.

**Comment by somyaranjan26** [comment]
Actually @Adyasha8105, there is only one issue per participant in each project.

**Comment by Adyasha8105** [comment]
okay @somyaranjan26
