### ISSUE TITLE
Enhance icon designs

### ISSUE THREAD

**Issue by sharmaaditya570191** [sharmaaditya570191/BossY#7]
Enhance icon designs for boss machine, minions and million dollar idea.

**Comment by Samriddhi25** [comment]
I want to take up this issue.

**Comment by sharmaaditya570191** [comment]
Sure. Go ahead @Samriddhi25 .

**Comment by Satzyakiz** [comment]
I would like to contribute to this issue as a part of GSSoC 2020.

**Comment by Samriddhi25** [comment]
Please review the PR

**Comment by Chetanjain10** [comment]
@sharmaaditya570191, please assign me this issue. I want to work on it

**Comment by Samriddhi25** [comment]
@sharmaaditya570191  please review my PR #21 for this issue.
