### ISSUE TITLE
Create Schema for Work using Mongoose

### ISSUE THREAD

**Issue by sharmaaditya570191** [sharmaaditya570191/BossY#72]
Everything in Mongoose starts with a Schema. Each schema maps to a MongoDB collection and defines the shape of the documents within that collection. This tasks involves using Mongoose to create schema for `Work`. You can refer to the `createWork` function in `server/db.js` file to complete this task.

**Comment by ashishnagpal2498** [comment]
Hi @sharmaaditya570191  I would like to work on this issue.

**Comment by shwetagurnani** [comment]
Please assign me this issue

**Comment by Satyam3976** [comment]
Please assign this issue to me as I have no issue to work on currently. I have already submitted my PR for the issues assigned to me:)

**Comment by BhuwanChandra** [comment]
@sharmaaditya570191 I would like to work on this issue. please assign me.
