### ISSUE TITLE
Create schema for Meeting using Mongoose

### ISSUE THREAD

**Issue by sharmaaditya570191** [sharmaaditya570191/BossY#74]
You can refer to `createMeeting` function in `server/db.js` to make a schema for `Meetings` using Mongoose.

**Comment by NikitaMasand** [comment]
I would like to work on this issue.

**Comment by shwetagurnani** [comment]
Please assign me this issue

**Comment by Satyam3976** [comment]
Please assign this issue to me as I have no issue to work on currently. I have already submitted my PR for the issues assigned to me:)

**Comment by BhuwanChandra** [comment]
@sharmaaditya570191 I would like to work on this issue. please assign me.

**Comment by shreyakapoor08** [comment]
@sharmaaditya570191 Can I work on this issue ?
