### ISSUE TITLE
Design footer for BossY

### ISSUE THREAD

**Issue by sharmaaditya570191** [sharmaaditya570191/BossY#75]
This includes designing a nice footer for the app.

**Comment by BhuwanChandra** [comment]
@sharmaaditya570191 @somyaranjan26 I would like to work on this issue. please assign me.

**Comment by Adyasha8105** [comment]
@sharmaaditya570191 Can I also work on this issue?

**Comment by somyaranjan26** [comment]
> @sharmaaditya570191 @somyaranjan26 Can I also work on this issue?

As you know one participant can work one issue at a time in a project. As @BhuwanChandra already assigned for this issue so, right now we can't assign you this issue. 

@sharmaaditya570191 if you have any suggestions about any feature or design for this project, tell us on slack, if we find it appropriate we will create an issue and directly assign you.

**Comment by BhuwanChandra** [comment]
@somyaranjan26 @sharmaaditya570191 can you tell me what I need to include in the footer?

**Comment by sharmaaditya570191** [comment]
Please wait a bit for the footer component.

**Comment by sharmakeshav10** [comment]
@sharmaaditya570191 I would like to work on this issue.
