### ISSUE TITLE
Create a cookies policy page for the app

### ISSUE THREAD

**Issue by sharmaaditya570191** [sharmaaditya570191/BossY#77]
This includes creating a policy page for cookies which is similar to this:-
![image](https://user-images.githubusercontent.com/42587159/78459624-e4fc2f00-76d7-11ea-8ce7-56b329c256df.png)

**Comment by shreyakapoor08** [comment]
@sharmaaditya570191 Can I work on this issue? 
I am working on converting the lighter theme and just some minor changes are left.
