### ISSUE TITLE
Add pre-commit hooks

### ISSUE THREAD

**Issue by jamesjose03** [sharmaaditya570191/BossY#85]
**Is your feature request related to a problem? Please describe.**  
As of now, there are no pre-commit hooks.

**Describe the solution you'd like**  
Add prettier and husky as pre-commit hooks for proper code formatting and styling.

**Describe alternatives you've considered**  
N/A

**Additional context**
N/A

**Comment by jamesjose03** [comment]
Pls assign this issue to me. I am a Gssoc participant

**Comment by sharmaaditya570191** [comment]
I would be configuring the linter with some custom rules that follow `prettier` and `standard.js` rules in some time. We do not need to add this at the moment. I am opening other issues which you can take. Thanks for your interest.
