### ISSUE TITLE
Restructure the project using the MVC pattern

### ISSUE THREAD

**Issue by Endowmissy** [sharmaaditya570191/BossY#87]
**Is your feature request related to a problem? Please describe.**  
The project needs to be restructured for easy arrangement and access especially the back-end files

**Describe the solution you'd like**  
A src folder needs to be created for the backend files, this will contain other backend folders too, the api.js file should be a route folder and be separated

**Describe alternatives you've considered**  

**Additional context**
I will do this, kindly assign it to me

**Comment by sharmaaditya570191** [comment]
After I merge all PR's related to the back end migration to MongoDB I will restructure and most probably create a separate repository for maintaining the back end. Thanks for your interest.
