### ISSUE TITLE
Create navigation bar component

### ISSUE THREAD

**Issue by sharmaaditya570191** [sharmaaditya570191/BossY#89]
You have to create a `function` component in React to replicate the following `navbar`. All styling should be in `scss`.  
![image](https://user-images.githubusercontent.com/42587159/79191172-9e2ed780-7e43-11ea-9957-7d3157847436.png)
The `navbar` should change to this on clicking the search button:-
![image](https://user-images.githubusercontent.com/42587159/79191380-0da4c700-7e44-11ea-8590-1d8a9b9072ac.png)  
You can remove the cart icon from the `navbar`

**Comment by Satyam3976** [comment]
Can I work on this?

**Comment by PritiShaw** [comment]
@sharmaaditya570191  is this issue available?

**Comment by Satyam3976** [comment]
No @PritiShaw , this issue is already assigned.
