### ISSUE TITLE
Improve the README.md file

### ISSUE THREAD

**Issue by sharmaaditya570191** [sharmaaditya570191/BossY#9]
Make the documentation more informative and descriptive.

**Comment by vipuldcoder** [comment]
I am interested with the issue.

**Comment by ranjal007** [comment]
I would like to work on this issue 
please assign it to me for gssoc20.

**Comment by annu12340** [comment]
I would also like to work on it

**Comment by abhishekjain35** [comment]
I would like to work on this...

**Comment by punisherz** [comment]
Its will be an honour to work on that issue

**Comment by sharmaaditya570191** [comment]
@vipuldcoder you can take this up. Others can have a look at other  beginner friendly issues. I will open more easy issues soon.

**Comment by Basilleaf24** [comment]
@sharmaaditya570191 I would like to do the documentation part in a detailed manner, pls assign me this issue

**Comment by punisherz** [comment]
@sharmaaditya570191  Can i work on this issue 
is anybody assigned?

**Comment by sharmaaditya570191** [comment]
@vipuldcoder had been assigned this issue earlier.

**Comment by vipul-aggarwal-099** [comment]
In Progress.

**Comment by shreyakapoor08** [comment]
@sharmaaditya570191 Can I work on this ?
