### ISSUE TITLE
Create footer component

### ISSUE THREAD

**Issue by sharmaaditya570191** [sharmaaditya570191/BossY#93]
You have to create a function component in React to replicate the same:-  
![image](https://user-images.githubusercontent.com/42587159/79192723-df74b680-7e46-11ea-8863-ec35ffdb2f59.png)  
Use `svg` format for the designs and do the remaining styling using `scss`.

**Comment by Satyam3976** [comment]
Please assign me this issue, I want to work on it

**Comment by ampsteric** [comment]
I can get this done...
