### ISSUE TITLE
Create 2nd page component

### ISSUE THREAD

**Issue by sharmaaditya570191** [sharmaaditya570191/BossY#95]
Create a function component in React to replicate the following:-  
![image](https://user-images.githubusercontent.com/42587159/79193494-5e1e2380-7e48-11ea-8d9b-4e9837b26014.png)  
![image](https://user-images.githubusercontent.com/42587159/79193903-2b285f80-7e49-11ea-9b6b-5b341a7e71be.png)

Use `scss` for styling.

**Comment by ashishnagpal2498** [comment]
Can I work on this issue @sharmaaditya570191

**Comment by ampsteric** [comment]
I can create this..
please assign
